### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by jrmoulton** [lapce/floem#650]
There are a few things left that I'd like to see done before 0.2.0. Hopefully that can happen very soon

- [x] #618 Rethink the API for creating elements with the builder pattern (also related #621)
- [x] #648 
- [x] #620 
- [x] Merge this todo app example as an example of a slightly more complex app #658 
- [x] Fix view transition example #662 
- [x] #665
- [x] #669
- [x] #682 
- [x] #671
- [x] Release/announce

**Comment by jrmoulton** [comment]
I had been planning on working more on the documentation before the next release but at this point I think it would just be good to get a release out as soon as possible

**Comment by dzhou121** [comment]
Thanks for organising this. We've made tons of changes since 0.1.0

**Comment by jrmoulton** [comment]
I've gotten everything done/merged that I considered blocking for the next release

**Comment by charlescgs** [comment]
I really appreciate your hard work and the effort placed into it @jrmoulton! Floem is improving so fast recently - mainly because of your contribution; thank you!
